### ISSUE TITLE
Parameters for Blackcoin BLK 

### ISSUE THREAD

**Issue by michelvankessel** [spesmilo/electrumx#105]
Hi, we are currently testing electrum with our new wallet software
https://gitlab.com/blackcoin/blackcoin-more

In the past Blackcoin was added, and we are now verifying the code below. We would like to understand some of the parameters currently used at /electrumx/lib/coins.py#L1578

Specifically the parameters starting from DAEMON on, except RPC_PORT. Is there an explanation for these? We want to make sure the correct values are used!

class Blackcoin(ScryptMixin, Coin):
NAME = "Blackcoin"
SHORTNAME = "BLK"
NET = "mainnet"
P2PKH_VERBYTE = bytes.fromhex("19")
P2SH_VERBYTES = [bytes.fromhex("55")]
WIF_BYTE = bytes.fromhex("99")
GENESIS_HASH = ('000001faef25dec4fbcf906e6242621d'
'f2c183bf232f263d0ba5b101911e4563')

DAEMON = daemon.LegacyRPCDaemon
TX_COUNT = 4594999
TX_COUNT_HEIGHT = 1667070
TX_PER_BLOCK = 3
RPC_PORT = 15715
REORG_LIMIT = 5000

**Comment by SomberNight** [comment]
See https://electrumx-spesmilo.readthedocs.io/en/latest/environment.html#envvar-REORG_LIMIT
and https://github.com/spesmilo/electrumx/commit/42ad745b2b241c90d1f2a80e3ad68e89d24067ab

**Comment by michelvankessel** [comment]
Thank you for the information. This is very helpful.

One more thing. Can you explain something about: DAEMON = daemon.LegacyRPCDaemon ?

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrumx/blob/42ad745b2b241c90d1f2a80e3ad68e89d24067ab/electrumx/server/daemon.py#L341

**Comment by michelvankessel** [comment]
Great! We are currently running some modified settings, and we removed the class LegacyRPCDaemon(Daemon): 
https://github.com/michelvankessel/electrumx/commit/e5be71e3a240fb27377cf8663aeb45b3d840419c

Syncing is way faster!  Thank you for your help!
