### ISSUE TITLE
How to fix issue blockchain.headers.subscribe and server.version?

### ISSUE THREAD

**Issue by odomdev** [spesmilo/electrumx#126]
1- E/StratumClient: Failed call
com.coinomi.stratumj.messages.MessageException: {"code":-32601,"message":"unknown method "blockchain.headers.subscribe""}:

2- com.coinomi.stratumj.messages.MessageException: {"code":-32601,"message":"unknown method "server.version""}:
at com.coinomi.stratumj.StratumClient.run(StratumClient.java:198)

3- E/StratumClient: Failed call
    com.coinomi.stratumj.messages.MessageException: {"code":-32601,"message":"unknown method \"blockchain.address.subscribe\""}: 
        at com.coinomi.stratumj.StratumClient.run(StratumClient.java:198)

May i know your advise how to fix it ? I use electrumx 1.16 ? I think it could be wrong version of com.coinomi.stratumj.messages's electrumx.

**Comment by SomberNight** [comment]
> I use electrumx 1.6

That version is ~2.5 years old, please update.

> unknown method "blockchain.address.subscribe"

That method has indeed been deprecated and even removed now.
The others should work though.

> `com.coinomi.stratumj`

You should probably ask the maintainers/developers of that package.

How are you running electrumx? Also, please link to the client you are using.

**Comment by odomdev** [comment]
Sorry I used electrumx 1.16 not 1.6

**Comment by odomdev** [comment]
electrumx 1.16 is running fine.  how can I know those removal method changed to ?

**Comment by SomberNight** [comment]
see https://electrumx-spesmilo.readthedocs.io/en/latest/protocol.html

**Comment by odomdev** [comment]
can you explain show me 
blockchain.headers.subscribe change to  ?
server.version change to. ?
blockchain.address.subscribe change to ?

I try to see those document but I don't understand.

**Comment by odomdev** [comment]
Why no protocol change doc in v1.16 ?

**Comment by SomberNight** [comment]
The versions mentioned there are re the "protocol version", which is independent of the version of ElectrumX.
The latest protocol version is 1.4.2.

**Comment by odomdev** [comment]
Hi,
if method below is removed from latest version of electrumx. how can we fix it at front end side ?

blockchain.headers.subscribe.
server.version
blockchain.address.subscribe

Thanks

**Comment by SomberNight** [comment]
I am sorry but I don't have time to write code for you.

**Comment by odomdev** [comment]
Just tell me how to fix i can fix it.
