### ISSUE TITLE
struct.error: 'H' format requires 0 <= number <= 65535

### ISSUE THREAD

**Issue by Justin11111a** [spesmilo/electrumx#132]
May 27 17:07:49 bohol electrumx_server.py[1755]: flush_id = pack('>H', self.flush_count)
May 27 17:07:49 bohol electrumx_server.py[1755]: struct.error: 'H' format requires 0 <= number <= 65535

how to fix this ?

We are using https://github.com/bauerj/electrumx-installer .

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrumx/issues/88
