### ISSUE TITLE
wallet client continously disconnects and reconnects with "socket.send() raised exception." error on electrumx server.

### ISSUE THREAD

**Issue by skythreefly** [spesmilo/electrumx#142]
ElectrumX and electrum wallet are on same localhost. I imported few addresses to watch and i got the following error on electrumx server. The wallet continuously connects and reconnects.

_INFO:MemPool:1,030 txs 1.49 MB touching 9,928 addresses
INFO:MemPool:1,149 txs 1.53 MB touching 10,529 addresses
INFO:MemPool:compact fee histogram: [(6.0, 120674), (2.0, 117632), (1.9, 360445), (1.1, 97364), (1.0, 85
5062)]
INFO:MemPool:1,260 txs 1.56 MB touching 10,882 addresses
INFO:MemPool:1,356 txs 1.59 MB touching 11,333 addresses
INFO:ElectrumX:[53] disconnected.  Sent 7,164,089 bytes in 804 messages
INFO:ElectrumX:[54] SSL 192.168.2.217:57817, 1 total
INFO:ElectrumX:[54] disconnected.  Sent 6,491,633 bytes in 609 messages
INFO:ElectrumX:[55] SSL 192.168.2.217:57818, 1 total
INFO:ElectrumX:[56] SSL 192.168.2.217:57819, 1 total
INFO:ElectrumX:[57] SSL 192.168.2.217:57820, 1 total
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
INFO:ElectrumX:[58] SSL 192.168.2.217:57821, 1 total
INFO:ElectrumX:[59] SSL 192.168.2.217:57822, 1 total
INFO:ElectrumX:[59] disconnected.  Sent 10,139,847 bytes in 1,671 messages
INFO:ElectrumX:[60] SSL 192.168.2.217:57823, 1 total
INFO:ElectrumX:[61] SSL 192.168.2.217:57824, 1 total
INFO:ElectrumX:[62] SSL 192.168.2.217:57825, 1 total
INFO:ElectrumX:[63] SSL 192.168.2.217:57826, 1 total
INFO:ElectrumX:[64] SSL 192.168.2.217:57827, 1 total
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
socket.send() raised exception.
INFO:MemPool:compact fee histogram: [(9.5, 101352), (3.0, 149122), (2.0, 39075), (1.9, 360874), (1.1, 100777), (1.0, 886289)]
INFO:ElectrumX:[65] SSL 192.168.2.217:57828, 1 total
INFO:ElectrumX:[66] SSL 192.168.2.217:57829, 1 total
INFO:ElectrumX:[67] SSL 192.168.2.217:57830, 1 total
INFO:ElectrumX:[68] SSL 192.168.2.217:57833, 1 total
INFO:ElectrumX:[69] SSL 192.168.2.217:57846, 1 total
INFO:ElectrumX:[70] SSL 192.168.2.217:57847, 1 total
INFO:ElectrumX:[71] SSL 192.168.2.217:57848, 1 total_

**Comment by skythreefly** [comment]
Addresses i am monitoring: [https://paste.ubuntu.com/p/pyhg3R6hJw/](https://paste.ubuntu.com/p/pyhg3R6hJw/)

**Comment by SomberNight** [comment]
Why do you think this is an issue with the server?
Please check and share the [logs created by the client](https://electrum.readthedocs.io/en/latest/faq.html#how-to-enable-debug-logging).

**Comment by skythreefly** [comment]
Wallet creates the following log:
`  ERROR | interface.[electrumx:55] | disconnecting due to GracefulDisconnect(RPCError(1, 'history too large'))`
so the address i'm watching having large history. I think this should be notified to user because the user things there's something wrong with wallet or server.

**Comment by SomberNight** [comment]
see https://github.com/spesmilo/electrum/issues/4315
