### ISSUE TITLE
memory leak in recent code

### ISSUE THREAD

**Issue by cipig** [spesmilo/electrumx#172]
this is the RAM usage for my electrum server (i compact DB/restart once a week):
![image](https://user-images.githubusercontent.com/32116761/158202757-73f363ff-aa34-4ce2-9584-81b3911dc397.png)
since couple of weeks it uses much more memory then it did before

**Comment by SomberNight** [comment]
Any idea about specific commits?
Also, to be clear, does it also happen with current HEAD (7e53936f34d2f1c979c64f91d15d6745fb8103c2)?

**Comment by cipig** [comment]
no idea, but must be one of the last 10 commits, after Jan 28, after https://github.com/spesmilo/electrumx/commit/3f12f288a442d4c3429de0a813c6355a0132633f
i am using latest master branch, but not 100% sure that all servers were already restarted with this version, some may be missing the last 3 commits... do you think the memleak might have been introduced after Jan 28, but already fixed in the last 3 commits?
i will restart everything now to be sure all servers are on latest master

**Comment by cipig** [comment]
all servers are running at least versions that have both those commits
in the meantime i am sure the memleak is still there... a server running latest master was restarted yesterday and the electrumx server already uses 12GB RAM (used to be 5)

**Comment by TrickyRaccoons** [comment]
I don't think it is a commit causing the memory leak. My server is impacted by the memory leak since the DDOS against it started. I think the memory leak is caused by the large amount of attempted connections by the botnet.

**Comment by cipig** [comment]
i run couple dozen different coins, some have a very low number of connections, but they are all affected
peer discovery is also off on all coins, `PEER_DISCOVERY = self`
i could try to go back to an older version, before the python 3.8 change... if the problem is not solved i will have to, since this version will crash my server sooner or later with OOM (automatic restart of all coins every week will not be enough to compensate for the memleak)
drawback is that i then have the random crashes back (which were solved in the last commits), so i will wait couple days more before reverting to older version

**Comment by cipig** [comment]
the situation is the same
![image](https://user-images.githubusercontent.com/32116761/160282037-0ad46b39-656b-4522-904c-ecb1905b6980.png)
coins that were using 5GB RAM before are now using 30GB, till restarted once a week
will downgrade to https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc and see what happens

**Comment by shsmith** [comment]
My servers started showing this same leakage when I updated from ubuntu 18.04 (python 3.7) to 20.04 (python 3.8). I suspect Python 3.8 is somehow missing a fix from 3.7.

**Comment by SomberNight** [comment]
@shsmith do you mean that with same electrumx commit some python versions have a memleak but others not?

**Comment by shsmith** [comment]
Yes, that is what I think happened. After the OS+python upgrade the leak started. I did the upgrade on two servers on 2/19/2022. I may have done a get pull on the same day, but I think the leak was triggered by the python version change rather than any recent git commit.

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/161240725-50e9defe-a7ee-4b25-82cd-84bfb02ae140.png)
the last 2 "hills" are from https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc
looks like the leak is not that big... unfortunately this version crashes on websockets requests and need to be restarted, so the chart is not for an entire week.

**Comment by cipig** [comment]
bigger picture
![image](https://user-images.githubusercontent.com/32116761/161525415-f23a9a3d-7d91-4a7a-914b-b317b6149dc5.png)
the last 3 hills are with https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc
guess it's mainly related to OS+python 3.9... it all started with that here too... funny is that i did the OS update to get the newer python version to be able to run latest electrumx (previous debian had python 3.7)
could it be related to some python modules? i would suspect aiorpcx, that was the "big" update... i have 0.22.1, the latest one
this is my config for this particular coin
```
COIN = Komodo
DB_DIRECTORY = /electrumdb/KMD
DAEMON_URL = http://xxxxx:xxxxxx@127.0.0.1:7771/
SERVICES = tcp://:10001,rpc://:8001,ssl://:20001,wss://:30001
EVENT_LOOP_POLICY = uvloop
PEER_DISCOVERY = self
MAX_SESSIONS = 5000
INITIAL_CONCURRENT = 100
COST_SOFT_LIMIT = 0
COST_HARD_LIMIT = 0
SSL_CERTFILE = /home/electrum/server.crt
SSL_KEYFILE = /home/electrum/server.key
MAX_SEND = 2000000
```
same as before the leak

**Comment by cipig** [comment]
switched back to latest commit and the memory usage rises faster then with https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc
![image](https://user-images.githubusercontent.com/32116761/162161153-f21d062f-0a3c-41e0-a667-e51bfa406d38.png)
last hill is latest commit, the 3 before that are https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc, all the other ones are also latest commit
switching now back to ee2c78e590a2794e1353acf7080d6eee2e71f60b (before the aiorpcx update) to see what happens

**Comment by cipig** [comment]
![image](https://user-images.githubusercontent.com/32116761/162440190-aaedf5ba-83cd-4465-a66c-e5a9848d1606.png)
ee2c78e590a2794e1353acf7080d6eee2e71f60b does not have the memleak... aiorpcX-0.18.7 with same python 3.9 on same server with debian 11

**Comment by shsmith** [comment]
> https://github.com/spesmilo/electrumx/commit/ee2c78e590a2794e1353acf7080d6eee2e71f60b does not have the memleak...

Same on Ubuntu server 20.04. Leak is gone. 

![electrumx_mem-day (1)](https://user-images.githubusercontent.com/859149/162556153-6055834a-7fff-4d14-96da-49264d8d5688.png)

**Comment by SomberNight** [comment]
I've found the leak, it's in aiorpcx. See https://github.com/kyuupichan/aiorpcX/issues/46

**Comment by SomberNight** [comment]
Please test with current master when you have time.

**Comment by cipig** [comment]
the memleak is fixed, thanks
