### ISSUE TITLE
Can't connect properly to my electrumx server

### ISSUE THREAD

**Issue by wang899** [spesmilo/electrumx#189]
Hi!

Ive tried now for some days to put up two electrum servers on my servers that just collecting dust

They all up and running with 50001, but for some reason i cant connect to them on that port, so struggled hours checking what it could be and notice i could connect if i typed 

ipaddress:50001:t 

That ":t" in the end made me able to connect and i really confused why it need that?, how to fix so it becomes only "ip:port" and not "ip:port:t" ?

**Comment by SomberNight** [comment]
The last part of the connection string in the client, `t` or `s`, is the protocol.
`t` stands for plaintext TCP. `s` is SSL/TLS over TCP.
When omitted, `s` is the default.
You should configure your server to also serve over SSL on some port, and then the client can connect to that without `...:t`.

**Comment by wang899** [comment]
Ahhh

Thank you bunch!, still here looking for it but couldnt find answer until now when you typed

This is my current .conf

SERVICES = tcp://0.0.0.0:50001

I just update it to 

SERVICES = tcp://0.0.0.0:50001,SSL://0.0.0.0:50002 i guess?  and follow the steps how to generate key on on the wiki?
