### ISSUE TITLE
blockchain.transaction.get not returning tx.vin[].txid

### ISSUE THREAD

**Issue by educob** [spesmilo/electrumx#191]
Hi.

I am running the electrumX against a regtest bitcoind.
When getting a tx I am not getting information about the vin.txid so I can't know where the utxos or the spent transaction outputs are.

How can I get this information?

Thanks.

**Comment by soichisumi** [comment]
blockchain.scripthash.listunspent returns utxos of scriptHash.

https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-listunspent

Due to the way the blockchain works, if you don't use this convenience method, you will not be able to know the utxo unless you aggregate all transactions of all previous blocks or use a third-party API.

Can this help you?

**Comment by educob** [comment]
Thanks for answering.
I am not sure i understand your answer.

I have seen that some free testnet electrumX servers returns enough tx
information to construct the history of a bitocin address (they return
tx.vin[].txid. So there is no need to call blockchain.scripthash.listunspent
method.
But others don't return the vin[].txid. And then even calling
blockchain.scripthash.listunspent only serves to know which tx outputs
haven't been spent but not in which tx the rest have been spent.

My electrumX connected to regtest doesn't return tx.vin[].txid. Is it a
matter of electrumX version?

The method I use to compose and address history is from blueWallet:
https://github.com/BlueWallet/BlueWallet/blob/master/blue_modules/BlueElectrum.js
Method: getTransactionsFullByAddress in line 381.
It expects tx to return vin[].txid.

Thanks again.

**Comment by soichisumi** [comment]
>  I have seen that some free testnet electrumX servers returns enough tx information to construct the history of a bitocin address (they return tx.vin[].txid).

How did you confirm this?

The get_history api used by https://github.com/BlueWallet/BlueWallet returns tx_hash and height, so not returning vin.txid is documented behavior.
https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-history

**Comment by soichisumi** [comment]
Hi. The transaction appears to be a coinbase transaction, and since a coinbase transaction has no parent vin, it is correct that there is no txid in the vin.

Due to the way bitcoin-based blockchains work, if you get a coinbase transaction, the response will look like this.

**Comment by educob** [comment]
Hi.

Thanks for you time.

Regards.
