### ISSUE TITLE
Clients cannot connect to my server

### ISSUE THREAD

**Issue by HotCrypt** [spesmilo/electrumx#194]
Hi,
I correctly installed Electrumx (clearnet) on Raspberry 4 8go as well as Btc core v22 with onlynet=ipv6(i don't want onion). 
I would like to solve these problems please:

`WARNING:Env: reduction of the maximum number of sessions from 2500 to 674 because your limit of open files is 1024`
Do you know where the file is to modify this directly?

Another thing, I don't get any incoming connection, I use `electrumx_rpc getinfo`:

` "tx hashes cache": "0 lookups 0 hits 0 entries"`

Peers works, I have 92 good peers, my personal ip is also present.

Thank you ✌️

**Comment by SomberNight** [comment]
> `WARNING:Env: reduction of the maximum number of sessions from 2500 to 674 because your limit of open files is 1024`
Do you know where the file is to modify this directly?

Depends on how you are launching electrumx. e.g.:
https://github.com/spesmilo/electrumx/blob/fb037fbd23b8ce418cd67d68bbf8d32e69ecef62/contrib/systemd/electrumx.service#L10

> Another thing, I don't get any incoming connection

Can you connect to your own server?

**Comment by HotCrypt** [comment]
> > `WARNING:Env: reduction of the maximum number of sessions from 2500 to 674 because your limit of open files is 1024`
> 
> Do you know where the file is to modify this directly?
> 
> 
> 
> Depends on how you are launching electrumx. e.g.:
> 
> https://github.com/spesmilo/electrumx/blob/fb037fbd23b8ce418cd67d68bbf8d32e69ecef62/contrib/systemd/electrumx.service#L10

****hi, thanks for your help. 
I looked and my file is ok: 8192.
It maybe not be here to change my problem limit.

> 
> > Another thing, I don't get any incoming connection
> 
> 
> 
> Can you connect to your own server?

****Yes, I’m well connected, here are my variables:

**Comment by HotCrypt** [comment]
~ $ electrumx_rpc getinfo
{
    "coin": "BitcoinSegwit",
    "daemon": "localhost:8332/",
    "daemon height": 757272,
    "db height": 757272,
    "db_flush_count": 2757,
    "groups": 0,
    "history cache": "0 lookups 0 hits 0 entries",
    "merkle cache": "0 lookups 0 hits 0 entries",
    "peers": {
        "bad": 1,
        "good": 115,
        "never": 0,
        "stale": 0,
        "total": 116
    },
    "pid": 4243,
    "request counts": {
        "blockchain.block.header": 1,
        "blockchain.headers.subscribe": 4,
        "getinfo": 1,
        "server.features": 4,
        "server.peers.subscribe": 4,
        "server.version": 4
    },
    "request total": 18,
    "sessions": {
        "count": 1,
        "count with subs": 0,
        "errors": 0,
        "logged": 0,
        "pending requests": 1,
        "subs": 0
    },
    "tx hashes cache": "0 lookups 0 hits 0 entries",
    "txs sent": 0,
    "uptime": "01h 16m 08s",
    "version": "ElectrumX 1.16.0"
   `

**Comment by SomberNight** [comment]
In your log you have:

> `INFO:SessionManager:advertising service ssl://90.89.48.32:50002`

I see electrumx is configured as:
```
export PUBLIC_IP=$(curl -s http://whatismyip.akamai.com/)
export REPORT_SERVICES=ssl://$PUBLIC_IP:50002
```

However, my client cannot connect to `90.89.48.32:50002`.

**Comment by HotCrypt** [comment]
Ok thank you, yes I noticed that clients can’t connect to me.

Do I change by:
`REPORT_SERVICS=ssl://90.89.48.32:50002` ?

**Comment by SomberNight** [comment]
>> Can you connect to your own server?
>
> *Yes, I’m well connected

and now you say:

> Ok thank you, yes I noticed that clients can’t connect to me.

... confusing. Not sure what you meant originally, but the answer then should have been "no".

-----

> Do I change by:
> `REPORT_SERVICS=ssl://90.89.48.32:50002` ?
> 
> And after that, can I delete the variable?:
> `export PUBLIC_IP=$(curl -s http://whatismyip.akamai.com/)`

No, that won't work. You need an open port that you can listen on.
Typically you would either need a publicly routable IP address, or at least some service that has one and can forward a port to you. Alternatively you can run a Tor `.onion` service.

**Comment by HotCrypt** [comment]
> >> Can you connect to your own server?
> 
> >
> 
> > *Yes, I’m well connected
> 
> 
> 
> and now you say:
> 
> 
> 
> > Ok thank you, yes I noticed that clients can’t connect to me.
> 
> 
> 
> ... confusing. Not sure what you meant originally, but the answer then should have been "no".
> 
> 
> 
> -----
> 
> 
> 
> > Do I change by:
> 
> > `REPORT_SERVICS=ssl://90.89.48.32:50002` ?
> 
> > 
> 
> > And after that, can I delete the variable?:
> 
> > `export PUBLIC_IP=$(curl -s http://whatismyip.akamai.com/)`
> 
> 
> 
> No, that won't work. You need an open port that you can listen on.
> 
> Typically you would either need a publicly routable IP address, or at least some service that has one and can forward a port to you. Alternatively you can run a Tor `.onion` service.

Port 50002 is open.

**Comment by SomberNight** [comment]
I've tested now with `$ telnet 90.89.48.32 50002`, and that port is not open.
I think you might be confused about external/routable IPs. Closing as there is no bug here.

**Comment by HotCrypt** [comment]
Problem solved thank you very much for your help, I’m really sorry:

The port was well open but only for my IP address 🤦‍♂️. I changed this and immediately saw incoming connections 😀, it works properly.

**Comment by HotCrypt** [comment]
Hi,

I have electrumX, btc full node (incom10/10output) and an LND node with channel on a raspberry4 8go hdd 2to, graphic version (from time to time I need to access the internet from the raspberry).

How much RAM do I have to assign to electrumX for it to work properly please?

I assigned 4500mo to btc node.

Do you have any other tips to optimize my ram and cpu?

Thanks again
