### ISSUE TITLE
error while connecting to BSV RPC endpoints 

### ISSUE THREAD

**Issue by hardikd88** [spesmilo/electrumx#231]
I am running electrumx 1.16.0 along with BSV external RPC endpoints. In my electrumx.conf file, I have configured this BSV endpoints and then electrumx started to sync the chain but after certain point it stopped to sync and now giving error. 
can anyone help me from the electrum side how can i solve this ?? I have also checked that my endpoint is working fine without electrumx. I need it to work with electrumx.  

Thanks in advance. 

Error = electrumx_server[28670]: ERROR:Daemon:daemon error: Response payload is not completed.  Retrying occasionally...

**Comment by ecdsa** [comment]
no support for bsv here
