### ISSUE TITLE
python-rocksdb and rocksdb 6.x are missing from newer distributions and preventing usage of electrumx

### ISSUE THREAD

**Issue by eugenesan** [spesmilo/electrumx#236]
Ubuntu 22.04 seems to be the last distro to provide python-rocksdb and rocksdb 6.x.
PIP version of python-rocksdb is obsolete and git version won't build with newer RocksDB.

Are there any solutions/plans to continue using electrumx in the future?

**Comment by SomberNight** [comment]
You can always just use leveldb. In fact that is the default.
But yeah, it's unfortunate that rocksdb does not have maintained bindings for python.
