### ISSUE TITLE
Build fails on Fedora 39 (worked on 38) - plyvel doesn't build

### ISSUE THREAD

**Issue by calebadavis** [spesmilo/electrumx#241]
Just upgraded fedora 38->39. Electrumx server now fails to start, and trying to build from latest 1.16 source fails with a lot of indecipherable auto-generated python->c++ binding warnings (deprecated member variables and whatnot).

In fact, the python3 leveldb project appears to be removed from fedora 39 entirely.

Is there a workaround? It looks like nobody is maintaining python leveldb for redhat.

https://bugzilla.redhat.com/show_bug.cgi?id=2220305

**Comment by koniiiik** [comment]
This has been fixed in the 1.5.1 release of plyvel (see https://github.com/wbolster/plyvel/issues/158) – you can always install e-x in a venv if your distribution doesn't have a maintainer for the dependencies.
