### ISSUE TITLE
version not the latest

### ISSUE THREAD

**Issue by ArmanTheParman** [spesmilo/electrumx#251]
Following the docs, using latest commit on github, electrumx installing as 1.16
how to get latest version, 1.20.0?

**Comment by SomberNight** [comment]
> how to get latest version, 1.20.0?

Why do you think that is the latest version? I guess that version number is for kyuupichan/electrumx. (`electrumx` on pypi)
For this repo, 1.16.0 is the latest tag atm. (`e-x` on pypi)

**Comment by ArmanTheParman** [comment]
Thanks, I got confused
