### ISSUE TITLE
Time-based groups?

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrumx#26]
Like everyone, my server is under constant DDoS. Currently ElectrumX has a simple cost-based mitigation, that works for individual sessions but also groups sessions together based on their /24 network address and also a time-window when the session was created. The network-based grouping kind of works, but I don't get the time-based bucketing. 

If the server is under constant load, the time-based groups will always be over budget and therefore all sessions will get throttled, regardless whether they are legit or not. Sooner or later, they will disconnect. Am I missing something, or is this type of protection contra-productive? Is anyone using this in production anyway?

If no-one is using it, shouldn't it be removed?

**Comment by SomberNight** [comment]
I am not sure why kyuupichan thought it would be a good idea, originally.
I agree, it only seems useful if the DDOS is short-lived / burst-like, which is just not the case in practice it seems.
So yes, we can remove it.
