### ISSUE TITLE
Can't install using docker

### ISSUE THREAD

**Issue by edsonPrimo** [spesmilo/electrumx#279]
I got the following error when trying to build the Docker image using the Dockerfile in the contrib folder

` File "/tmp/pip-install-8fpwr_tm/python-rocksdb_0daf6b7625e44ce3b107fa57e0fa2b7b/.eggs/Cython-3.0.11-py3.9-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 130, in build_extension
10.68           new_ext = cythonize(
10.68         File "/tmp/pip-install-8fpwr_tm/python-rocksdb_0daf6b7625e44ce3b107fa57e0fa2b7b/.eggs/Cython-3.0.11-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1154, in cythonize
10.68           cythonize_one(*args)
10.68         File "/tmp/pip-install-8fpwr_tm/python-rocksdb_0daf6b7625e44ce3b107fa57e0fa2b7b/.eggs/Cython-3.0.11-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1321, in cythonize_one
10.68           raise CompileError(None, pyx_file)
10.68       Cython.Compiler.Errors.CompileError: rocksdb/_rocksdb.pyx`

**Comment by ElderBlade** [comment]
I'm also getting the same error. How did you resolve this?

**Comment by edsonPrimo** [comment]
> I'm also getting the same error. How did you resolve this?

I removed rocksdb

```
 FROM python:3.9.16-bullseye AS builder

WORKDIR /usr/src/app

RUN python -m venv venv \
    && venv/bin/pip install --no-cache-dir e-x[rapidjson]==1.16.0


FROM python:3.9.16-slim-bullseye


ENV SERVICES="tcp://:50001"
ENV COIN=Bitcoin
ENV DB_DIRECTORY=/var/lib/electrumx
ENV DAEMON_URL="http://bitcoin:fMcSOyoiEdK_IwK2eXJ3AiTeCGWGEsw4hrSLI9Y7BBs@bitcoin-node:48332"
ENV ALLOW_ROOT=true
ENV DB_ENGINE=leveldb
ENV MAX_SEND=10000000
ENV BANDWIDTH_UNIT_COST=50000
ENV CACHE_MB=2000

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app .

VOLUME /var/lib/electrumx

RUN mkdir -p ./data && ulimit -n 1048576

CMD ["/usr/src/app/venv/bin/python", "/usr/src/app/venv/bin/electrumx_server"]
```
