### ISSUE TITLE
Get scripthash for known scriptPubKey in python？

### ISSUE THREAD

**Issue by xiaoqge** [spesmilo/electrumx#32]
have to query addresses in ElectrumX server. How do I generate scripthash for a known scriptPubKey in python? If my bitcoin wallet address is 1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ

**Comment by SomberNight** [comment]
https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-basics.html#script-hashes
https://github.com/spesmilo/electrum/blob/8d7370d897314d8542906aecc6a45cc949651f77/electrum/bitcoin.py#L475-L477
