### ISSUE TITLE
Problem with parameter id:0

### ISSUE THREAD

**Issue by xiaoqge** [spesmilo/electrumx#33]
First of all thank you for your help, I have a little doubt, here is my example：

```
import socket
import json
from time import sleep
import sys,os
ABSPATH = os.path.abspath(os.path.realpath(os.path.dirname(__file__)))
ABSPATH = ABSPATH
sys.path.append(ABSPATH)
from bitcoin import *

port = 50001
host = '127.0.0.1'


hash = address_to_scripthash("386eAUqL3ZNZPmHeABXLo658DTQuJeLzUR")

content = {
    "method": "blockchain.scripthash.get_balance",
    "params": [hash],
     "id": 0
}

def electrumx(host, port, content):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((host, port))
    sock.sendall(json.dumps(content).encode('utf-8')+b'\n')
    sleep(0.5)
    sock.shutdown(socket.SHUT_WR)
    res = ""
    while True:
        data = sock.recv(1024)
        if (not data):
            break
        res += data.decode()
    print(res)
    sock.close()

electrumx(host, port, content)
```

What does id:0 mean in the following code?

```
content = {
    "method": "blockchain.scripthash.get_balance",
    "params": [hash],
     "id": 0
}
```
Why don’t I return the result when I delete id:0, what is the meaning of it?

**Comment by SomberNight** [comment]
see https://www.jsonrpc.org/specification#request_object

`id` lets you have a client that sends many requests on the wire, without waiting for responses for each,
and then collect the responses later and tie them to the requests sent using the same `id` field in the reponses.

The protocol does not guarantee that responses are sent in-order for the requests. Some requests might take longer to compute, during which the server might answer the cheaper requests.

**Comment by xiaoqge** [comment]
thank you very much
