### ISSUE TITLE
ElectrumX server keeps crashing randomly

### ISSUE THREAD

**Issue by Robot1982** [spesmilo/electrumx#41]
From version 1.15.0 ElectrumX server keeps crashing randomly (sometimes daily). If you need more info let me know.

Debian 10.4
Python 3.7.3

Jul 13 05:52:49 server1 electrumx_server[10865]: INFO:Prefetcher:cancelled; prefetcher stopping
Jul 13 05:52:49 server1 electrumx_server[10865]: INFO:SessionManager:closing down server for rpc://127.0.0.1:8000
Jul 13 05:52:49 server1 electrumx_server[10865]: INFO:SessionManager:closing down server for ssl://all_interfaces:50002
Jul 13 05:52:49 server1 electrumx_server[10865]: INFO:ElectrumX:[156216] disconnected whilst throttled
Jul 13 05:52:50 server1 electrumx_server[10865]: INFO:Controller:shutting down
Jul 13 05:52:50 server1 electrumx_server[10865]: INFO:Controller:shutdown complete
Jul 13 05:52:50 server1 electrumx_server[10865]: ERROR:electrumx:ElectrumX server terminated abnormally
Jul 13 05:52:50 server1 electrumx_server[10865]: Traceback (most recent call last):
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx_server", line 35, in main
Jul 13 05:52:50 server1 electrumx_server[10865]:     asyncio.run(controller.run())
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jul 13 05:52:50 server1 electrumx_server[10865]:     return loop.run_until_complete(main)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
Jul 13 05:52:50 server1 electrumx_server[10865]:     return future.result()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/lib/server_base.py", line 125, in run
Jul 13 05:52:50 server1 electrumx_server[10865]:     await server_task
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/lib/server_base.py", line 98, in serve
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.serve(shutdown_event)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/controller.py", line 134, in serve
Jul 13 05:52:50 server1 electrumx_server[10865]:     await group.spawn(wait_for_catchup())
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.join()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Jul 13 05:52:50 server1 electrumx_server[10865]:     raise task.exception()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 681, in fetch_and_process_blocks
Jul 13 05:52:50 server1 electrumx_server[10865]:     await group.spawn(self._process_prefetched_blocks())
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.join()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Jul 13 05:52:50 server1 electrumx_server[10865]:     raise task.exception()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 642, in _process_prefetched_blocks
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.check_and_advance_blocks(blocks)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 220, in check_and_advance_blocks
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self._maybe_flush()
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 354, in _maybe_flush
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.flush(True)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 348, in flush
Jul 13 05:52:50 server1 electrumx_server[10865]:     await self.run_in_thread_with_lock(flush)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 202, in run_in_thread_with_lock
Jul 13 05:52:50 server1 electrumx_server[10865]:     return await asyncio.shield(run_in_thread_locked())
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 201, in run_in_thread_locked
Jul 13 05:52:50 server1 electrumx_server[10865]:     return await run_in_thread(func, *args)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 68, in run_in_thread
Jul 13 05:52:50 server1 electrumx_server[10865]:     return await get_event_loop().run_in_executor(None, func, *args)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Jul 13 05:52:50 server1 electrumx_server[10865]:     result = self.fn(*self.args, **self.kwargs)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/block_processor.py", line 347, in flush
Jul 13 05:52:50 server1 electrumx_server[10865]:     self.estimate_txs_remaining)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "/home/electrumx/electrumx/server/db.py", line 225, in flush_dbs
Jul 13 05:52:50 server1 electrumx_server[10865]:     self.flush_state(batch)
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "plyvel/_plyvel.pyx", line 634, in plyvel._plyvel.WriteBatch.__exit__
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "plyvel/_plyvel.pyx", line 617, in plyvel._plyvel.WriteBatch.write
Jul 13 05:52:50 server1 electrumx_server[10865]:   File "plyvel/_plyvel.pyx", line 91, in plyvel._plyvel.raise_for_status
Jul 13 05:52:50 server1 electrumx_server[10865]: plyvel._plyvel.CorruptionError: b'Corruption: corrupted compressed block contents'
Jul 13 05:52:51 server1 systemd[1]: electrumx.service: Succeeded.

**Comment by whizz** [comment]
This looks like there is something wrong with the data. Possibly it got corrupted on the disk. My guess is you will need to delete the data and reinitialize.

**Comment by whizz** [comment]
You can also theoretically try to repair the database. Change into your data directory and run:
```
python3 -c "import plyvel; plyvel.repair_db('hist')"
python3 -c "import plyvel; plyvel.repair_db('utxo')"
```

**Comment by Robot1982** [comment]
Thanks! I will try to repair the database and post the results here.

**Comment by Robot1982** [comment]
Repairing the database didn't help. It got stock (for more than 1 day) with:

Jul 15 14:15:38 server1 electrumx_server[491]: INFO:History:DB shut down uncleanly.  Scanning for excess history flushes...

I am now trying to reinitialize the database. It is still syncing since more than 40 hours. I will post the results after the sync is done.

**Comment by curious0101** [comment]
"I will post the results after the sync is done."

No update since then, I assume this is resolved and not an electrumX issue but bad disk/hardware etc? Perhaps can be closed.

**Comment by Robot1982** [comment]
Sorry for not replying sooner, but the sync took a long time, also because it was crashing during the sync (there is another open issue for this #30) and I also did a full resync of bitcoind just to be sure. Now it works since about a week without a problem. I guess the problem was really the corrupt database. I will close this. Thanks for the help!
