### ISSUE TITLE
Not able to withdraw my BTC,showing error

### ISSUE THREAD

**Issue by mohit1250** [spesmilo/electrumx#51]
I have BTC in hardware and I have tried it withdrawing electrum wallet showing error and locked for 24 hrs and everytime when I m trying to withdraw it locked.
Please help me

**Comment by curious0101** [comment]
What is BTC in hardware? Can you show us screenshot of the error you are getting? What you mean locked for 24 hrs?

**Comment by mohit1250** [comment]
See it's not an hardware error it's the operating system not granting access and whenever trying to access it's blocking access for 24 hrs

**Comment by mohit1250** [comment]
I m using Transcend pendrive in which my BTC is stored

**Comment by curious0101** [comment]
Please provide screenshot of the error you are getting

**Comment by ecdsa** [comment]
wrong repository, electrumx is the server
