### ISSUE TITLE
DAEMON_URL definition unclear

### ISSUE THREAD

**Issue by github-broke-my-old-account** [spesmilo/electrumx#57]
Is DAEMON_URL supposed to be json-rpc address or bitcoin-protocol address?

**Comment by SomberNight** [comment]
It is for bitcoind rpc access.
e.g. `DAEMON_URL="username:password@hostname:port"`

**Comment by github-broke-my-old-account** [comment]
> e.g. `DAEMON_URL="username:password@hostname:port"`

Thanks.  BTW that's not an eg.  An eg is eg 

    DAEMON_URL="bill:wibble@127.0.0.4:8223

eg is an 'example', not the form again.
