### ISSUE TITLE
Print complete tor v3 onion addresses for rpc command peers 

### ISSUE THREAD

**Issue by sumBTC** [spesmilo/electrumx#7]
*First of all: thanks for the support of Bitcoin and Electrum!*

The command `electrumx_rpc peers` prints a maximum of 30 characters for the host item. However, onion v3 addresses are 56 characters without the ".onion" extension and thus 62 characters with the ".onion" extension. If a user wants to see how many onion addresses are connected to his electrumx server (for example via `electrumx_rpc peers | grep onion | wc -l`) only the version 2 tor addresses will contribute.

It would be nice if the peers rpc command shows the ".onion" extension for all tor addresses.

EDIT: I found that this can be achieved by changing the two occurrences of 30 in electrumx/lib/text.py into 62

**Comment by JustinTArthur** [comment]
Thanks, @sumBTC. I'm not a common `electrumx_rpc` user. How does the output look with the 62-character address field? Do you have to expand a typical terminal window to get it aligned?

If this is what most of the server operators would want, happy to make it the default length for that field, otherwise we can add a command line option to expand the field width.

**Comment by sumBTC** [comment]
@JustinTArthur thanks for looking into this issue.

> Do you have to expand a typical terminal window to get it aligned?

Yes, if you expand the terminal window enough, the output is aligned again and looks like this (for only 2 lines of output shown of many similar lines)

```
sw6tua3xl24gsmi264zaep6seppjyrkyucpsmuxnjzyt3f3j6swshad.onion good   50001 50002 ElectrumX 1.14.0   1.4 1.4.2          01h 32m 28s 01h 32m 45s     0                 peer                
btc.rossbennetts.com                                          good   50081 50082 ElectrumX 1.15.0   1.4 1.4.2          01h 32m 45s 01h 32m 54s     0                 peer 220.233.178.199
```
The next upgrade of Bitcoin Core will support tor [v3](https://decrypt.co/44640/bitcoins-next-upgrade-will-support-tor-v3-addresses?utm_source=reddit&utm_medium=social&utm_campaign=sm) addresses. It's slowly becoming the default tor version everywhere, so that justifies making it the default length for that field.
