### ISSUE TITLE
How to cache data to memory

### ISSUE THREAD

**Issue by xiaoqge** [spesmilo/electrumx#73]
Due to the previous electrumx memory leak, I added the server to 128G memory. Now the memory problem is solved, but the remaining memory is close to 110G. How can I cache all the rocksdb data in the memory to improve the query speed, so that no ssd hard disk is needed.

**Comment by SomberNight** [comment]
That's a lot of RAM. Not sure.
The easiest thing would be to create a [RAM disk](https://unix.stackexchange.com/questions/66329/creating-a-ram-disk-on-linux) -- but that's not a cache of course, and if power goes out (do you have a UPS?), you lose the data.

**Comment by xiaoqge** [comment]
> That's a lot of RAM. Not sure.
> The easiest thing would be to create a [RAM disk](https://unix.stackexchange.com/questions/66329/creating-a-ram-disk-on-linux) -- but that's not a cache of course, and if power goes out (do you have a UPS?), you lose the data.

Thank you for your help. I think this is a good way. I regularly backup electrumx data to a physical disk.
