### ISSUE TITLE
how to force using Tor to broadcast new transactions?

### ISSUE THREAD

**Issue by monkey-jsun** [spesmilo/electrumx#82]
I have set up bitcoin core with the following options:
```
txindex=1
server=1
disablewallet=1
walletbroadcast=0
```

I have set up electrumx as follows:
```
export DB_DIRECTORY=$HOME/.electrumx/db
export DAEMON_URL="http://$(cat "$HOME/.bitcoin/.cookie")@localhost:8332"
export COIN=Bitcoin
export SERVICES=tcp://:50001,ssl://:50002
export SSL_CERTFILE=/etc/ssl/certs/ssl-cert-snakeoil.pem
export SSL_KEYFILE=/etc/ssl/private/ssl-cert-snakeoil.key
electrumx_server
```

I have an electrum wallet that only connects to my own electrumx server.  When I create a transaction, apparently the transaction is broadcasted out and carried out successfully.  What is the route through which transaction gets broadcasted?  Specifically is my electrumx server braodcasting the transaction to its peers?  Or is my bitcoin core daemon sending to its peers?  Is there a way force the broadcast of our own transactions going through Tor only, while keeping other transaction relay using the usual route?

Thanks.

**Comment by whizz** [comment]
Electrumx only talks to your Bitcoin Core node to send the transaction. If you setup your node to talk only Tor, it should be private in this regard.

**Comment by monkey-jsun** [comment]
Thanks, @whizz 

I searched around and realized that bitcoin core will broadcast transaction to its peers no matter how peers are connected (incoming or outgoing).  So to be anonymous, one would have to do two things: a) use Tor for outgoing connections; b) set up an anonymous onion service for incoming connections.

I was too lazy to do b).  For a) it is straightforward.  Just add the following to bitcoin.conf file:

```
# Listening for peers, enabled by default except when 'connect' is being used
listen=0

# outgoing traffic use onion/tor only (default any)
proxy=127.0.0.1:9050
onlynet=onion
```
