### ISSUE TITLE
how to check electrumx server status and fingerprint etc?

### ISSUE THREAD

**Issue by monkey-jsun** [spesmilo/electrumx#85]
I have a server up and running now.  I wonder if there are any online tools or commnadline tools that I can use to check its status (e.g., version number, banner, etc)

Thanks!

**Comment by SomberNight** [comment]
see https://electrumx-spesmilo.readthedocs.io/en/latest/rpc-interface.html#getinfo

**Comment by whizz** [comment]
FWIW, I am using this primitive PHP script to pull the metrics and make them available over JSON/HTTP:

```php
<?php

$output = '';
$r = exec('/usr/local/bin/electrumx_rpc getinfo', $output);
header('content-type: application/json');
echo implode('',$output);
```

You can then poll this from any metrics collection system periodically.

**Comment by smmalis37** [comment]
I have a script that runs a `nc -nz "${public_ip}" 50002` to ensure that my server is not only up, but reachable from outside my LAN.

**Comment by monkey-jsun** [comment]
Thanks for the info.  However, none of them seem ideal.  RPC only works locally (and does not give details such as banner).  nc only tells you whether connection to the port is successful.  

I'm little surprised there isn't "telnet-like" tool either standalone or online.  Is it hard to write one?  Any pointer on the electrumx protocol or any existing code sample?

**Comment by SomberNight** [comment]
> Thanks for the info. However, none of them seem ideal. RPC only works locally 

`getinfo` is intended to be used by the server admin, it is intentionally not exposed as part of the public protocol APIs.

-----

Re the banner specifically, you can get using the electrum protocol itself indeed (that's the point of it).

```
printf '{"id": 1, "method": "server.version", "params": ["testing", "1.4"]}\n{"id": 2, "method": "server.banner"}\n' | nc testnet.qtornado.com 51001
```

```
openssl s_client -connect testnet.qtornado.com:51002
{"id": 1, "method": "server.version", "params": ["testing", "1.4"]}
{"id": 2, "method": "server.banner"}
```

**Comment by monkey-jsun** [comment]
Thanks, @SomberNight This is super helpful!  On the openssl method,  the connection seems to be made. But how do I enter and end the input stream?  Currently it gives the following error.

```
[jsun@www script]$ openssl s_client -connect us.netspectrum.com:50002
socket: Bad file descriptor
connect:errno=9
```
