### ISSUE TITLE
Error installing electrumx

### ISSUE THREAD

**Issue by PsySc0rpi0n** [spesmilo/electrumx#91]
I'm using Debian Buster and running a full bitcoin node.
I tried to install electrumx from the readthedocs.io instructions.

I ran this commands to install dependencies:
`sudo apt install python3-aiohttp`
`pip3 install pylru`
`git clone https://github.com/spesmilo/electrumx.git`
`pip3 install .`

But I got this error:
https://pastebin.com/M7PyQyMC

Then I tried issuing:
`pip3 install plyvel`
but got this error:
https://pastebin.com/6tgRxAGc

and
`pip3 install .[rocksdb,ujson]`
more errors:
https://pastebin.com/9QXD9tVq

What am I missing? Help, please!

Edited;
I was missing 2 libraries: **libleveldb-dev** && **python3-leveldb**
But I still can't install RocksDB with theabove command. Error is the same:
`pip3 install .[rocksdb,ujson]`

https://pastebin.com/9QXD9tVq

**Comment by SomberNight** [comment]
> But I got this error:
> https://pastebin.com/M7PyQyMC
> 
> Then I tried issuing:
> `pip3 install plyvel`
> but got this error:
> https://pastebin.com/6tgRxAGc

plyvel only provides prebuilt wheels for amd64 architechture (see https://pypi.org/project/plyvel/#files), maybe you are on a different arch; in any case, pip decided to grab the source distributable instead and is now failing to build from that

from https://plyvel.readthedocs.io/en/latest/installation.html#build-and-install-plyvel
> To build from source, make sure you have a shared LevelDB library and the development headers installed where the compiler and linker can find them. For Debian or Ubuntu something like `apt-get install libleveldb1v5 libleveldb-dev` should suffice.

-----

>  But I still can't install RocksDB with theabove command. Error is the same:
> `pip3 install .[rocksdb,ujson]`

The `plyvel` package contains python bindings for LevelDB.
The `rocksdb` package is python bindings for RocksDB.
Which do you intend to use?

If you want RocksDB, try something like this:
`apt-get install librocksdb-dev libsnappy-dev libbz2-dev libz-dev liblz4-dev`

**Comment by PsySc0rpi0n** [comment]
I'll stick to the default. I think I don't need to install RocksDB.
So, I think it is all well now. But I have a few questions that I couldn't get answer from the readthedocs.io site.

1 - Is this server going to download and verify another entire copy of the bitcoin blockchain? I already have it on the bitcoin full node I'm running.

2 - The docs says we need to point out a DB path. This path is a new path or is it the bitcoin core blockchain path? It is not very clear. Or better, it is clear it wants a new folder for a database, but then it says that it will download and reindex the blockchain.But does this electrumx needs a second copy of the entire blockchain when we already have the one from our bitcoin core node?

**Comment by SomberNight** [comment]
It will not duplicate data that bitcoind already has, except in trivial amounts.
It will build its own database consisting of indices that bitcoind does NOT have, to be able to efficiently serve client.

**Comment by PsySc0rpi0n** [comment]
> It will not duplicate data that bitcoind already has, except in trivial amounts.
> It will build its own database consisting of indices that bitcoind does NOT have, to be able to efficiently serve client.

So, how big will the database be?
