### ISSUE TITLE
Problems with large transactions and problems with a lot of address history

### ISSUE THREAD

**Issue by Teimoon** [spesmilo/electrumx#94]
Hello there.

This bitcoin-tx
0048c164bf6da763bcae4983d570af709d96310987c6ae3cbde4f3ecb81a0e57
with many outputs delivers the error:
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 99998 (char 99997)
command: get_from_electrum('blockchain.transaction.get',[txhash,True])

Another issue:
An very busy address with many transactions delivers the error:
#{'jsonrpc': '2.0', 'error': {'code': 1, 'message': 'history too large'}, 'id': 0}
command: get_from_electrum('blockchain.scripthash.get_history', scripthash)

any ideas?

thank you.

**Comment by ecdsa** [comment]
the transaction loads normally in Electrum
I have no idea what `get_from_electrum` is, but you should not ask us to debug it

"history too large" is a server error message. we are working on a protocol update to deal with those cases.

**Comment by Teimoon** [comment]
I ask my electrumx server via socket and json from python.
The first error "unterminated string" is probably a buffer error. 

I was not complaining. I like your work.

Because of the second error, i will wait for the protocol update.

Thank you for answering.
